In [1]:
import numpy as np

### Fun with numpy arrays

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f'Types of elements in the array: {arr.dtype}')
print(f'Array type:{type(arr)}')
print(f'Array shape: {arr.shape}')

reshaped_arr = arr.reshape(2, 5)
print(f'\nNew shape: {reshaped_arr.shape}')

print(f'\nArray as a list: {arr.tolist()}')

print(f'\nMean of the array: {arr.mean()}')
print(f'Max value in array: {arr.max()}')
print(f'Min value in array: {arr.min()}')
print(f'Array standard deviation: {arr.std():.5f}')
print(f'Cummulative sum of array: {arr.cumsum()}')

Types of elements in the array: int32
Array type:<class 'numpy.ndarray'>
Array shape: (10,)

New shape: (2, 5)

Array as a list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Mean of the array: 4.5
Max value in array: 9
Min value in array: 0
Array standard deviation: 2.87228
Cummulative sum of array: [ 0  1  3  6 10 15 21 28 36 45]


### Helpful numpy functions

In [17]:
np.linspace(0, 10, 15)  # 15 evenly spaced elements between 0 and 10

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [18]:
np.arange(0, 10, 2)  # evenly spaced range of values between 0 and 10, step 2

# how does this differ from range(0, 10, 2) ?

array([0, 2, 4, 6, 8])

In [25]:
unsorted_arr = np.array(['a', 'z', 'c', 'y'])
sort_order = np.argsort(unsorted_arr)

print(f'The proper sort order is: {sort_order}')
print(f'The first sorted value is: {unsorted_arr[sort_order[0]]}')
print(f'The last sorted value is: {unsorted_arr[sort_order[-1]]}')

The proper sort order is: [0 2 3 1]
The first sorted value is: a
The last sorted value is: z


In [26]:
np.random.normal(50, 10, 10)  # mean, std, number of elements

array([52.74218963, 47.04941039, 36.85520358, 41.34488499, 62.33456851,
       53.94876297, 59.78643509, 59.84302071, 51.86078859, 31.19983169])

### Collections

### Itertools

### Xml Element Tree

### Requests

### Beautiful Soup

### Machine Learning
 - University of Cincinnati professor Bradley Boehmke's site: https://uc-r.github.io/
 - Which college is best for you?  https://www.kaggle.com/code/apollostar/which-college-is-best-for-you